[tool.poetry]
name = "iac-tutorial"
version = "0.1.0"
description = ""
authors = ["Tobias Ecklebe <tobias.ecklebe@outlook.de>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
