version: '3'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - parent_image="jenkins/jenkins:2.319.3-jdk11"
    ports:
      - 8080:8080
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge