version: '3'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - parent_image=${PARENT_IMAGE}
    ports:
      - 8080:8080
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge