credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              description: "This is only the ID used on Jenkins, where behind different users\
            \ can be used."
              id: "skeleton-user"
              password: "admin"
              scope: GLOBAL
              username: "admin"
              usernameSecret: true
jenkins:
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  authorizationStrategy:
    projectMatrix:
      permissions:
        - "Agent/Build:jenkins-admins"
        - "Agent/Build:jenkins-slaves"
        - "Agent/Configure:jenkins-admins"
        - "Agent/Configure:jenkins-slaves"
        - "Agent/Connect:jenkins-admins"
        - "Agent/Connect:jenkins-slaves"
        - "Agent/Create:jenkins-admins"
        - "Agent/Create:jenkins-slaves"
        - "Agent/Delete:jenkins-admins"
        - "Agent/Delete:jenkins-slaves"
        - "Agent/Disconnect:jenkins-admins"
        - "Artifactory/Promote:jenkins-admins"
        - "Artifactory/Release:jenkins-admins"
        - "Build Failure Analyzer/RemoveCause:jenkins-admins"
        - "Build Failure Analyzer/UpdateCauses:jenkins-admins"
        - "Build Failure Analyzer/ViewCauses:jenkins-admins"
        - "Credentials/Create:jenkins-admins"
        - "Credentials/Delete:jenkins-admins"
        - "Credentials/ManageDomains:jenkins-admins"
        - "Credentials/Update:jenkins-admins"
        - "Credentials/View:jenkins-admins"
        - "Job/Build:jenkins-admins"
        - "Job/Cancel:jenkins-admins"
        - "Job/Configure:jenkins-admins"
        - "Job/Create:jenkins-admins"
        - "Job/Delete:jenkins-admins"
        - "Job/Discover:jenkins-admins"
        - "Job/Move:jenkins-admins"
        - "Job/Read:jenkins-admins"
        - "Job/Read:jenkins-viewers"
        - "Job/Workspace:jenkins-admins"
        - "Manage ownership/Jobs:jenkins-admins"
        - "Manage ownership/Nodes:jenkins-admins"
        - "Metrics/HealthCheck:jenkins-admins"
        - "Metrics/ThreadDump:jenkins-admins"
        - "Metrics/View:jenkins-admins"
        - "Overall/Administer:jenkins-admins"
        - "Overall/Administer:skeleton-admin"
        - "Overall/Read:jenkins-admins"
        - "Overall/Read:jenkins-viewers"
        - "Run/Delete:jenkins-admins"
        - "Run/Replay:jenkins-admins"
        - "Run/Update:jenkins-admins"
        - "SCM/Tag:jenkins-admins"
        - "View/Configure:jenkins-admins"
        - "View/Create:jenkins-admins"
        - "View/Delete:jenkins-admins"
        - "View/Read:jenkins-admins"
        - "View/Read:jenkins-viewers"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  disabledAdministrativeMonitors:
    - "jenkins.security.csrf.CSRFAdministrativeMonitor"
    - "jenkins.monitor.JavaVersionRecommendationAdminMonitor"
    - "hudson.model.UpdateCenter$CoreUpdateMonitor"
    - "jenkins.security.UpdateSiteWarningsMonitor"
    - "jenkins.security.QueueItemAuthenticatorMonitor"
    - "hudson.PluginManager$PluginDeprecationMonitor"
    - "jenkins.security.ResourceDomainRecommendation"
    - "hudson.diagnosis.ReverseProxySetupMonitor"
  labelAtoms:
    - name: "built-in"
    - name: "master"
  labelString: "master"
  log:
    recorders:
      - loggers:
          - level: "OFF"
            name: "org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver"
        name: "genericwebhook"
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false
  mode: EXCLUSIVE
  myViewsTabBar: "standard"
  numExecutors: 15
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
        - id: "skeleton-admin"
          name: "skeleton-admin"
          password: "admin"
          properties:
            - preferredProvider:
                providerId: "default"
            - mailer:
                emailAddress: "admin@example.com"
  slaveAgentPort: 50000
  updateCenter:
    sites:
      - id: "default"
        url: "https://updates.jenkins.io/update-center.json"
  views:
    - all:
        name: "all"
  viewsTabBar: "standard"
support:
  automatedBundleConfiguration:
    componentIds:
      - "AgentsConfigFile"
      - "ConfigFileComponent"
      - "OtherConfigFilesComponent"
      - "AboutBrowser"
      - "AboutJenkins"
      - "AboutUser"
      - "AdministrativeMonitors"
      - "AgentProtocols"
      - "BuildQueue"
      - "CustomLogs"
      - "DumpExportTable"
      - "EnvironmentVariables"
      - "FileDescriptorLimit"
      - "GCLogs"
      - "HeapUsageHistogram"
      - "ItemsContent"
      - "AgentsJVMProcessSystemMetricsContents"
      - "MasterJVMProcessSystemMetricsContents"
      - "JenkinsLogs"
      - "LoadStats"
      - "LoggerManager"
      - "Metrics"
      - "NetworkInterfaces"
      - "NodeMonitors"
      - "OtherLogs"
      - "ReverseProxy"
      - "RootCAs"
      - "RunningBuilds"
      - "SlaveCommandStatistics"
      - "SlaveLaunchLogs"
      - "SlaveLogs"
      - "AgentsSystemConfiguration"
      - "MasterSystemConfiguration"
      - "SystemProperties"
      - "TaskLogs"
      - "ThreadDumps"
      - "UpdateCenter"
      - "UserCount"
      - "SlowRequestComponent"
      - "HighLoadComponent"
      - "DeadlockRequestComponent"
      - "PipelineTimings"
      - "PipelineThreadDump"
    enabled: true
    period: 1
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
security:
  anonymizeSupportBundle:
    enabled: false
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  copyartifact:
    mode: PRODUCTION
  envInject:
    enableLoadingFromMaster: false
    enablePermissions: false
    hideInjectedVars: false
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  sSHD:
    port: 50000
unclassified:
  ansiColorBuildWrapper:
    colorMaps:
      - black: "#000000"
        blackB: "#4C4C4C"
        blue: "#1E90FF"
        blueB: "#4682B4"
        cyan: "#00CDCD"
        cyanB: "#00FFFF"
        green: "#00CD00"
        greenB: "#00FF00"
        magenta: "#CD00CD"
        magentaB: "#FF00FF"
        name: "xterm"
        red: "#CD0000"
        redB: "#FF0000"
        white: "#E5E5E5"
        whiteB: "#FFFFFF"
        yellow: "#CDCD00"
        yellowB: "#FFFF00"
      - black: "#000000"
        blackB: "#555555"
        blue: "#0000AA"
        blueB: "#5555FF"
        cyan: "#00AAAA"
        cyanB: "#55FFFF"
        defaultBackground: 0
        defaultForeground: 7
        green: "#00AA00"
        greenB: "#55FF55"
        magenta: "#AA00AA"
        magentaB: "#FF55FF"
        name: "vga"
        red: "#AA0000"
        redB: "#FF5555"
        white: "#AAAAAA"
        whiteB: "#FFFFFF"
        yellow: "#AA5500"
        yellowB: "#FFFF55"
      - black: "black"
        blackB: "black"
        blue: "blue"
        blueB: "blue"
        cyan: "cyan"
        cyanB: "cyan"
        green: "green"
        greenB: "green"
        magenta: "magenta"
        magentaB: "magenta"
        name: "css"
        red: "red"
        redB: "red"
        white: "white"
        whiteB: "white"
        yellow: "yellow"
        yellowB: "yellow"
      - black: "#2E3436"
        blackB: "#2E3436"
        blue: "#3465A4"
        blueB: "#3465A4"
        cyan: "#06989A"
        cyanB: "#06989A"
        defaultBackground: 0
        defaultForeground: 7
        green: "#4E9A06"
        greenB: "#4E9A06"
        magenta: "#75507B"
        magentaB: "#75507B"
        name: "gnome-terminal"
        red: "#CC0000"
        redB: "#CC0000"
        white: "#D3D7CF"
        whiteB: "#D3D7CF"
        yellow: "#C4A000"
        yellowB: "#C4A000"
    globalColorMapName: "xterm"
  artifactoryBuilder:
    jfrogPipelinesServer:
      bypassProxy: false
      connectionRetries: 3
      credentialsConfig:
        overridingCredentials: false
        username: "****"
      timeout: 300
    useCredentialsPlugin: false
  badgePlugin:
    disableFormatHTML: false
  bitbucketEndpointConfiguration:
    endpoints:
      - bitbucketCloudEndpoint:
          enableCache: false
          manageHooks: false
          repositoriesCacheDuration: 0
          teamCacheDuration: 0
  buildDiscarders:
    configuredBuildDiscarders:
      - "jobBuildDiscarder"
  buildFailureAnalyzer:
    doNotAnalyzeAbortedJob: false
    gerritTriggerEnabled: true
    globalEnabled: false
    graphsEnabled: false
    knowledgeBase: "localFile"
    maxLogSize: 0
    metricSquashingEnabled: false
    noCausesEnabled: false
    noCausesMessage: "No problems were identified. If you know why this problem occurred,\
      \ please add a suitable Cause for it."
    nrOfScanThreads: 3
    slackFailureCategories: "ALL"
    slackNotifEnabled: false
    testResultParsingEnabled: false
  buildStepOperation:
    enabled: false
  claimConfig:
    blockAutoRefreshWhileClaiming: false
    propagateToFollowingBuildsByDefault: false
    sendEmails: false
    sendEmailsForStickyFailures: false
    sortUsersByFullName: false
    stickyByDefault: true
  defaultFolderConfiguration:
    healthMetrics:
      - worstChildHealthMetric:
          recursive: true
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultContentType: "text/plain"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultTriggerIds:
      - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: -1
    precedenceBulk: false
    watchingEnabled: false
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "http://127.0.0.1:8080/github-webhook/"
  gitLabConnectionConfig:
    connections:
      - clientBuilderId: "autodetect"
        connectionTimeout: 10
        ignoreCertificateErrors: false
        readTimeout: 10
    useAuthenticatedEndpoint: true
  gitSCM:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  globalDefaultFlowDurabilityLevel:
    durabilityHint: PERFORMANCE_OPTIMIZED
  groovy:
    installations:
      - name: "Groovy 2.5.0"
        properties:
          - installSource:
              installers:
                - groovyInstaller:
                    id: "2.5.0"
  ivyBuildTrigger:
    extendedVersionMatching: false
  junitTestResultStorage:
    storage: "file"
  locale:
    ignoreAcceptLanguage: true
    systemLocale: "EN"
  location:
    adminAddress: "admin@example.com"
    url: "http://127.0.0.1:8080/"
  logParser:
    legacyFormatting: false
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  mavenModuleSet:
    localRepository: "default"
  naginatorPublisher:
    regexpTimeoutMs: 30000
  pipeline-model-docker:
    dockerLabel: "docker"
  pollSCM:
    pollingThreadCount: 10
  prismConfiguration:
    theme: PRISM
  simple-theme-plugin:
    elements:
      - cssUrl:
          url: "http://127.0.0.1:8080/userContent/jenkins.css"
      - cssText:
          text: |-
            .ui-resizable-handle {
             position: absolute;
             bottom: 0;
             background-color: #1f7313;
             width: 100%;
             height: 10px;
             cursor: row-resize;
             opacity: 0.1;
            }
            .ui-resizable-handle:hover {
             opacity: 0.6;
            }
  slackNotifier:
    botUser: false
    sendAsText: false
  splunkJenkinsInstallation:
    enabled: false
    globalPipelineFilter: true
    maxEventsBatchSize: 262144
    metadataHost: "127.0.0.1"
    port: 8088
    rawEventEnabled: true
    retriesOnError: 3
    useSSL: true
  subversionSCM:
    workspaceFormat: 8
  timestamper:
    allPipelines: true
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
  upstream:
    globalUpstreamFilterStrategy: UseOldest
  warningsParsers:
    consoleLogScanningPermitted: false
  whitelist:
    enabled: false
tool:
  git:
    installations:
      - home: "git"
        name: "Default"
  groovy:
    installations:
      - name: "Groovy 2.5.0"
        properties:
          - installSource:
              installers:
                - groovyInstaller:
                    id: "2.5.0"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
  powerShellInstallation:
    installations:
      - home: "powershell.exe"
        name: "DefaultWindows"
      - home: "pwsh"
        name: "DefaultLinux"
