version: '3'

services:
  bind:
    restart: always
    image: bind:9.16.1-20200423
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "10000:10000/tcp"
    volumes:
      - ./srv/docker/bind:/data
    build:
      context: .
      dockerfile: Dockerfile

