version: '3.4'
services:
  dev_env:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      # set the default kube config of this project to the defined path
      # https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#linux-1
      KUBECONFIG: /workspace/setup-03/kube_config
    volumes:
      # So that we can run docker can from inside the dev env container
      # https://devopscube.com/run-docker-in-docker/
      # https://hub.docker.com/_/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - ${WORKSPACE}:/workspace
      - ${USERHOME}:/root
    working_dir: /workspace
    user: root
    networks:
      - iac
    entrypoint: >-
      bash -c "echo This is our IaC development environment
      && /bin/bash"

networks:
  iac:
    driver: bridge
